# Generated by Django 4.1.2 on 2022-10-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nombre_medicamento',
            field=models.CharField(max_length=100),
        ),
    ]
