# Generated by Django 4.1.2 on 2022-10-08 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_medicoespecialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=35)),
                ('nombre_paciente', models.CharField(max_length=75)),
                ('paterno_paciente', models.CharField(max_length=75)),
                ('materno_paciente', models.CharField(max_length=75)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=5)),
                ('contacto', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='medicoespecialista',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=5),
        ),
        migrations.CreateModel(
            name='agendarCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_cita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cita', models.DateField(auto_now_add=True)),
                ('receta_medica', models.CharField(max_length=50)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.paciente')),
            ],
        ),
    ]
